from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np
from scipy.optimize import linear_sum_assignment

from matching_engine.optimization.candidate_generator import (
    MatchCandidate,
)


@dataclass(frozen=True)
class MatchAssignment:
    """
    Represents a final mentor-mentee assignment.

    Unlike MatchCandidate, this represents a decision made
    by the global optimizer.
    """

    mentor_id: str
    mentee_id: str
    score: float
    features: dict[str, float]


class MatchingOptimizer:
    """
    Globally optimize mentor-mentee assignments.

    The optimizer maximizes the total compatibility score
    while respecting mentor capacity.

    Important:

        CandidateGenerator
            ↓
        possible mentor/mentee pairs

        MatchingOptimizer
            ↓
        final assignments

    A mentee can receive at most one mentor.

    A mentor can receive multiple mentees, subject to
    their available capacity.
    """

    def optimize(
        self,
        candidates: Iterable[MatchCandidate],
        mentor_capacities: dict[str, int],
    ) -> list[MatchAssignment]:
        """
        Find the globally optimal mentor-mentee assignment.

        Args:
            candidates:
                Possible mentor-mentee pairings generated by
                CandidateGenerator.

            mentor_capacities:
                Available capacity for each mentor.

                Example:

                    {
                        "m1": 2,
                        "m2": 1,
                    }

        Returns:
            List of final MatchAssignment objects.

        Notes:
            - Each mentee receives at most one mentor.
            - A mentor cannot exceed their available capacity.
            - Only supplied candidates can be selected.
            - Candidates with invalid/non-positive capacity
              are ignored.
        """

        candidates = list(candidates)

        if not candidates:
            return []

        # --------------------------------------------------
        # Build mentor capacity slots
        # --------------------------------------------------

        mentor_slots: list[str] = []

        for mentor_id, capacity in mentor_capacities.items():
            if capacity <= 0:
                continue

            mentor_slots.extend(
                [mentor_id] * capacity
            )

        if not mentor_slots:
            return []

        # --------------------------------------------------
        # Get unique mentees
        # --------------------------------------------------

        mentee_ids = sorted(
            {
                candidate.mentee_id
                for candidate in candidates
            }
        )

        if not mentee_ids:
            return []

        # --------------------------------------------------
        # Index candidates
        # --------------------------------------------------

        candidate_lookup: dict[
            tuple[str, str],
            MatchCandidate,
        ] = {}

        for candidate in candidates:
            key = (
                candidate.mentee_id,
                candidate.mentor_id,
            )

            # If duplicate candidates exist for the same
            # pair, retain the highest score.
            existing = candidate_lookup.get(key)

            if (
                existing is None
                or candidate.score > existing.score
            ):
                candidate_lookup[key] = candidate

        # --------------------------------------------------
        # Build score matrix
        # --------------------------------------------------

        #
        # Rows    = mentees
        # Columns = mentor capacity slots
        #
        # Example:
        #
        # M1 capacity = 2
        # M2 capacity = 1
        #
        # columns:
        #
        # M1-slot-1 | M1-slot-2 | M2-slot-1
        #

        num_mentees = len(mentee_ids)
        num_slots = len(mentor_slots)

        scores = np.zeros(
            (num_mentees, num_slots),
            dtype=float,
        )

        for row, mentee_id in enumerate(
            mentee_ids
        ):
            for column, mentor_id in enumerate(
                mentor_slots
            ):
                candidate = candidate_lookup.get(
                    (
                        mentee_id,
                        mentor_id,
                    )
                )

                if candidate is not None:
                    scores[row, column] = candidate.score

        # --------------------------------------------------
        # Convert maximization into minimization
        # --------------------------------------------------

        #
        # scipy.linear_sum_assignment minimizes cost.
        #
        # We therefore use:
        #
        #     cost = -score
        #
        # Higher compatibility score becomes lower cost.
        #

        cost_matrix = -scores

        row_indices, column_indices = (
            linear_sum_assignment(cost_matrix)
        )

        # --------------------------------------------------
        # Convert optimizer result into assignments
        # --------------------------------------------------

        assignments: list[MatchAssignment] = []

        for row, column in zip(
            row_indices,
            column_indices,
        ):
            mentee_id = mentee_ids[row]
            mentor_id = mentor_slots[column]

            candidate = candidate_lookup.get(
                (
                    mentee_id,
                    mentor_id,
                )
            )

            # No candidate means this is an artificial
            # zero-score matrix entry. Do not create a match.
            if candidate is None:
                continue

            assignments.append(
                MatchAssignment(
                    mentor_id=candidate.mentor_id,
                    mentee_id=candidate.mentee_id,
                    score=candidate.score,
                    features=candidate.features,
                )
            )

        # Highest-quality assignments first.
        assignments.sort(
            key=lambda assignment: assignment.score,
            reverse=True,
        )

        return assignments

    def optimize_from_grouped_candidates(
        self,
        candidates_by_mentee: dict[
            str,
            list[MatchCandidate],
        ],
        mentor_capacities: dict[str, int],
    ) -> list[MatchAssignment]:
        """
        Convenience method for the dictionary returned by
        CandidateGenerator.generate().
        """

        candidates: list[MatchCandidate] = []

        for mentee_candidates in (
            candidates_by_mentee.values()
        ):
            candidates.extend(
                mentee_candidates
            )

        return self.optimize(
            candidates=candidates,
            mentor_capacities=mentor_capacities,
        )